//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app7.settings_files {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class permissions_settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static permissions_settings defaultInstance = ((permissions_settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new permissions_settings())));
        
        public static permissions_settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int manage_customers {
            get {
                return ((int)(this["manage_customers"]));
            }
            set {
                this["manage_customers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int customers_kshf_7sab {
            get {
                return ((int)(this["customers_kshf_7sab"]));
            }
            set {
                this["customers_kshf_7sab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int customers_mdeonee {
            get {
                return ((int)(this["customers_mdeonee"]));
            }
            set {
                this["customers_mdeonee"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int customers_paied_money {
            get {
                return ((int)(this["customers_paied_money"]));
            }
            set {
                this["customers_paied_money"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int open_pos {
            get {
                return ((int)(this["open_pos"]));
            }
            set {
                this["open_pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int sales_report {
            get {
                return ((int)(this["sales_report"]));
            }
            set {
                this["sales_report"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int manage_products {
            get {
                return ((int)(this["manage_products"]));
            }
            set {
                this["manage_products"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int manage_categories {
            get {
                return ((int)(this["manage_categories"]));
            }
            set {
                this["manage_categories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int manage_settings {
            get {
                return ((int)(this["manage_settings"]));
            }
            set {
                this["manage_settings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int manage_storages {
            get {
                return ((int)(this["manage_storages"]));
            }
            set {
                this["manage_storages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int storages_operations {
            get {
                return ((int)(this["storages_operations"]));
            }
            set {
                this["storages_operations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int manage_users {
            get {
                return ((int)(this["manage_users"]));
            }
            set {
                this["manage_users"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int manage_users_roles {
            get {
                return ((int)(this["manage_users_roles"]));
            }
            set {
                this["manage_users_roles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int manage_blackbox {
            get {
                return ((int)(this["manage_blackbox"]));
            }
            set {
                this["manage_blackbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int snd_qbd {
            get {
                return ((int)(this["snd_qbd"]));
            }
            set {
                this["snd_qbd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int snd_srf {
            get {
                return ((int)(this["snd_srf"]));
            }
            set {
                this["snd_srf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int snds_report {
            get {
                return ((int)(this["snds_report"]));
            }
            set {
                this["snds_report"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int manage_daily_brief {
            get {
                return ((int)(this["manage_daily_brief"]));
            }
            set {
                this["manage_daily_brief"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int manage_today_agle {
            get {
                return ((int)(this["manage_today_agle"]));
            }
            set {
                this["manage_today_agle"] = value;
            }
        }
    }
}
